openapi: 3.0.3
info:
  title: BOAS 서비스 통합 API
  description: BOAS 공지사항, 채용 및 제품 관리 시스템을 위한 API 명세서입니다.
  version: 1.4.0

servers:
  - url: /api/v1
    description: 기본 API 경로

tags:
  - name: Notice
    description: 공지사항 관련 사용자 API
  - name: Notice Admin
    description: 공지사항 관리자용 CRUD API
  - name: Recruit
    description: 채용공고 관련 사용자 API
  - name: Recruit Admin
    description: 채용공고 관리자용 CRUD API
  - name: Product
    description: 제품 관련 사용자 API
  - name: Product Admin
    description: 제품 관리자용 CRUD API

paths:
  # --- Notice API ---
  /notices:
    get:
      summary: 공지사항 목록 조회
      tags: [Notice]
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema: { $ref: '#/components/schemas/NoticeListResponse' }
    post:
      summary: 공지사항 작성
      tags: [Notice Admin]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title: { type: string }
                content: { type: string }
                files: { type: array, items: { type: string, format: binary } }
              required: [title, content]
      responses:
        '201':
          description: 등록 성공

  # --- Recruit API ---
  /recruits:
    get:
      summary: 채용공고 목록 조회 (업무/요건 포함)
      tags: [Recruit]
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema: { $ref: '#/components/schemas/RecruitListResponse' }

    post:
      summary: 채용공고 작성 (연관 테이블 자동 저장)
      tags: [Recruit Admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                status: { type: string }
                location: { type: string }
                type: { type: string }
                applyLink: { type: string, format: uri }
                recruit_duties: { type: array, items: { type: string }, description: "주요 업무 리스트 (recruit_duties 테이블 저장)" }
                recruit_requirements: { type: array, items: { type: string }, description: "자격 요건 리스트 (recruit_requirements 테이블 저장)" }
              required: [title, applyLink]
      responses:
        '201':
          description: 등록 성공

  /recruits/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: integer }
    get:
      summary: 채용공고 상세 조회
      tags: [Recruit]
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema: { $ref: '#/components/schemas/RecruitDetailResponse' }
    put:
      summary: 채용공고 수정
      tags: [Recruit Admin]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                status: { type: string }
                location: { type: string }
                type: { type: string }
                applyLink: { type: string, format: uri }
                recruit_duties: { type: array, items: { type: string } }
                recruit_requirements: { type: array, items: { type: string } }
      responses:
        '200':
          description: 수정 성공
    delete:
      summary: 채용공고 삭제
      tags: [Recruit Admin]
      responses:
        '200':
          description: 삭제 성공

  # --- Product API ---
  /products:
    get:
      summary: 제품 목록 조회
      tags: [Product]
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ProductListResponse' }
    post:
      summary: 제품 등록
      tags: [Product Admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                category: { type: string }
                image: { type: string }
                description: { type: string }
                detail: { type: string }
              required: [title, category]
      responses:
        '201':
          description: 등록 성공

components:
  schemas:
    # --- Recruit Schemas (연관 데이터 포함) ---
    RecruitItem:
      type: object
      properties:
        id: { type: integer }
        title: { type: string }
        status: { type: string }
        location: { type: string }
        type: { type: string }
        recruit_duties: { type: array, items: { type: string } }
        recruit_requirements: { type: array, items: { type: string } }
        createdAt: { type: string, format: date-time }

    RecruitListResponse:
      type: object
      properties:
        success: { type: boolean }
        data:
          type: array
          items: { $ref: '#/components/schemas/RecruitItem' }

    RecruitDetailResponse:
      type: object
      properties:
        success: { type: boolean }
        data: { $ref: '#/components/schemas/RecruitItem' }

    # --- 기타 공통 스키마 생략 (기존과 동일) ---
    NoticeListResponse: { type: object, properties: { success: { type: boolean }, data: { type: object } } }
    ProductListResponse: { type: object, properties: { success: { type: boolean }, data: { type: array } } }
