openapi: 3.0.3
info:
  title: BOAS 서비스 통합 API
  description: BOAS 공지사항, 채용 및 제품 관리 시스템을 위한 API 명세서입니다.
  version: 1.4.1

servers:
  - url: /api/v1
    description: 기본 API 경로

tags:
  - name: Notice
    description: 공지사항 관련 사용자 API
  - name: Notice Admin
    description: 공지사항 관리자용 CRUD API
  - name: Recruit
    description: 채용공고 관련 사용자 API
  - name: Recruit Admin
    description: 채용공고 관리자용 CRUD API
  - name: Product
    description: 제품 관련 사용자 API
  - name: Product Admin
    description: 제품 관리자용 CRUD API
  - name: Inquiry
    description: 1:1 문의 관련 사용자 API
  - name: Inquiry Admin
    description: 1:1 문의 관리자용 API

paths:
  # --- Inquiry API ---
  /inquiries:
    post:
      summary: 1:1 문의 등록
      tags: [Inquiry]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                email: { type: string }
                message: { type: string }
                isAgreed: { type: boolean, description: "개인정보 수집 동의 여부" }
              required: [name, message, isAgreed]
      responses:
        '201':
          description: 문의 등록 성공
    get:
      summary: 문의 목록 조회
      tags: [Inquiry Admin]
      parameters:
        - name: page
          in: query
          schema: { type: integer, default: 1 }
        - name: limit
          in: query
          schema: { type: integer, default: 10 }
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema: { $ref: '#/components/schemas/InquiryListResponse' }

  /inquiries/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: integer }
    get:
      summary: 문의 상세 조회
      tags: [Inquiry Admin]
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema: { $ref: '#/components/schemas/InquiryItem' }
    delete:
      summary: 문의 삭제
      tags: [Inquiry Admin]
      responses:
        '200':
          description: 삭제 성공

  # --- Notice API ---
  /notices:
    get:
      summary: 공지사항 목록 조회
      tags: [Notice]
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema: { $ref: '#/components/schemas/NoticeListResponse' }
    post:
      summary: 공지사항 작성
      tags: [Notice Admin]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title: { type: string }
                content: { type: string }
                files: { type: array, items: { type: string, format: binary } }
              required: [title, content]
      responses:
        '201':
          description: 등록 성공

  # --- Recruit API ---
  /recruits:
    get:
      summary: 채용공고 목록 조회 (업무/요건/링크 포함)
      tags: [Recruit]
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema: { $ref: '#/components/schemas/RecruitListResponse' }

    post:
      summary: 채용공고 작성 (연관 테이블 자동 저장)
      tags: [Recruit Admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                status: { type: string }
                location: { type: string }
                type: { type: string }
                applyLink: { type: string, format: uri }
                recruit_duties: { type: array, items: { type: string } }
                recruit_requirements: { type: array, items: { type: string } }
              required: [title, applyLink]
      responses:
        '201':
          description: 등록 성공

  /recruits/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: integer }
    get:
      summary: 채용공고 상세 조회
      tags: [Recruit]
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema: { $ref: '#/components/schemas/RecruitDetailResponse' }
    put:
      summary: 채용공고 수정
      tags: [Recruit Admin]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                status: { type: string }
                location: { type: string }
                type: { type: string }
                applyLink: { type: string, format: uri }
                recruit_duties: { type: array, items: { type: string } }
                recruit_requirements: { type: array, items: { type: string } }
      responses:
        '200':
          description: 수정 성공
    delete:
      summary: 채용공고 삭제
      tags: [Recruit Admin]
      responses:
        '200':
          description: 삭제 성공

  # --- Product API ---
  /products:
    get:
      summary: 제품 목록 조회
      tags: [Product]
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ProductListResponse' }
    post:
      summary: 제품 등록
      tags: [Product Admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                category: { type: string }
                image: { type: string }
                description: { type: string }
                detail: { type: string }
              required: [title, category]
      responses:
        '201':
          description: 등록 성공

components:
  schemas:
    # --- Recruit Schemas (지원링크 포함 필수!) ---
    RecruitItem:
      type: object
      properties:
        id: { type: integer }
        title: { type: string }
        status: { type: string }
        location: { type: string }
        type: { type: string }
        applyLink: { type: string, format: uri, description: "지원 페이지 외부 링크" }
        recruit_duties: { type: array, items: { type: string } }
        recruit_requirements: { type: array, items: { type: string } }
        createdAt: { type: string, format: date-time }

    RecruitListResponse:
      type: object
      properties:
        success: { type: boolean }
        data:
          type: array
          items: { $ref: '#/components/schemas/RecruitItem' }

    RecruitDetailResponse:
      type: object
      properties:
        success: { type: boolean }
        data: { $ref: '#/components/schemas/RecruitItem' }

    # --- 기타 공통 스키마 생략 ---
    NoticeListResponse: { type: object, properties: { success: { type: boolean }, data: { type: object } } }
    ProductListResponse: { type: object, properties: { success: { type: boolean }, data: { type: array } } }
    
    # --- Inquiry Schemas ---
    InquiryItem:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }
        email: { type: string }
        message: { type: string }
        isAgreed: { type: boolean }
        createdAt: { type: string, format: date-time }
        
    InquiryListResponse:
      type: object
      properties:
        success: { type: boolean }
        data:
          type: object
          properties:
            inquiries:
              type: array
              items: { $ref: '#/components/schemas/InquiryItem' }
            pagination:
              type: object
              properties:
                totalCount: { type: integer }
                totalPages: { type: integer }
                currentPage: { type: integer }
