openapi: 3.0.3
info:
  title: 공지사항 서비스 API
  description: BOAS 공지사항 관리 시스템을 위한 API 명세서입니다.
  version: 1.0.1

servers:
  - url: /api/v1
    description: 기본 API 경로

paths:
  /notices:
    get:
      summary: 공지사항 목록 조회
      description: 페이징 처리가 된 공지사항 목록을 반환합니다.
      tags:
        - Notice
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: 페이지 번호
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: 페이지당 조회 개수
      responses:
        '200':
          description: 성공적으로 목록을 조회함
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoticeListResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'

    post:
      summary: 공지사항 작성
      description: 새로운 공지사항을 등록합니다. 관리자 비밀번호 확인이 필요합니다.
      tags:
        - Notice Admin
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 200
                  description: 공지사항 제목
                content:
                  type: string
                  maxLength: 50000
                  description: 공지사항 본문
                password:
                  type: string
                  description: 관리자 비밀번호
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: 첨부파일 리스트
              required:
                - title
                - content
                - password
      responses:
        '201':
          description: 공지사항 등록 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoticeDetailResponse'
        '403':
          $ref: '#/components/responses/ForbiddenError'

  /notices/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: 공지사항 고유 ID
    get:
      summary: 공지사항 상세 조회
      description: 특정 ID의 공지사항 정보를 상세하게 조회합니다.
      tags:
        - Notice
      responses:
        '200':
          description: 상세 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoticeDetailResponse'
        '404':
          $ref: '#/components/responses/NotFoundError'
    put:
      summary: 공지사항 수정
      description: 기존 공지사항을 수정합니다. 관리자 비밀번호 확인이 필요합니다.
      tags:
        - Notice Admin
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 200
                  description: 수정할 제목
                content:
                  type: string
                  maxLength: 50000
                  description: 수정할 내용
                password:
                  type: string
                  description: 관리자 비밀번호
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: 추가할 파일
                removeFileIds:
                  type: string
                  description: 삭제할 파일 ID 리스트 (쉼표 구분)
              required:
                - password
      responses:
        '200':
          description: 수정 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoticeDetailResponse'
        '403':
          $ref: '#/components/responses/ForbiddenError'
    delete:
      summary: 공지사항 삭제
      description: 특정 공지사항을 삭제합니다. 관리자 비밀번호 확인이 필요합니다.
      tags:
        - Notice Admin
      parameters:
        - name: password
          in: query
          required: true
          schema:
            type: string
          description: 관리자 비밀번호
      responses:
        '200':
          description: 삭제 성공
          content:
            application/json:
              schema:
                type: object
                description: 삭제 결과 객체
                properties:
                  success:
                    type: boolean
                    description: 성공 여부
                  message:
                    type: string
                    description: 결과 메시지
                  data:
                    type: object
                    description: 삭제된 리소스 정보
                    properties:
                      id: { type: integer, description: "삭제된 아이디" }
                      deletedAt: { type: string, format: date-time, description: "삭제 일시" }
        '403':
          $ref: '#/components/responses/ForbiddenError'

components:
  schemas:
    # 1. 에러 응답 객체
    ErrorResponse:
      type: object
      description: 에러 응답 구조
      properties:
        success:
          type: boolean
          example: false
          description: 항상 false
        error:
          type: object
          description: 상세 에러 정보
          properties:
            code:
              type: string
              description: 에러 코드
            message:
              type: string
              description: 에러 메시지

    # 2. 공통 기본 응답
    BaseResponse:
      type: object
      description: 공통 응답 기본 구조
      properties:
        success:
          type: boolean
          description: 성공 여부
        message:
          type: string
          description: 응답 메시지

    # 3. 데이터 모델
    NoticeItem:
      type: object
      description: 공지사항 요약 정보
      properties:
        id: { type: integer, description: "ID" }
        title: { type: string, description: "제목" }
        author: { type: string, description: "작성자" }
        viewCount: { type: integer, description: "조회수" }
        hasAttachments: { type: boolean, description: "첨부파일 존재 여부" }
        createdAt: { type: string, format: date-time, description: "생성일" }

    Attachment:
      type: object
      description: 첨부파일 상세 정보
      properties:
        id: { type: integer, description: "파일 ID" }
        filename: { type: string, description: "저장된 파일명" }
        originalName: { type: string, description: "원본 파일명" }
        size: { type: integer, description: "파일 크기" }
        url: { type: string, description: "다운로드 URL" }

    Pagination:
      type: object
      description: 페이징 정보
      properties:
        currentPage: { type: integer }
        totalPages: { type: integer }
        totalCount: { type: integer }
        limit: { type: integer }
        hasNext: { type: boolean }
        hasPrev: { type: boolean }

    # 4. 최종 응답 스키마
    NoticeListResponse:
      type: object
      description: 공지사항 목록 응답
      properties:
        success: { type: boolean }
        data:
          type: object
          description: 공지사항 데이터와 페이징 정보
          properties:
            notices:
              type: array
              items:
                $ref: '#/components/schemas/NoticeItem'
            pagination:
              $ref: '#/components/schemas/Pagination'

    NoticeDetailResponse:
      type: object
      description: 공지사항 상세 응답
      properties:
        success: { type: boolean }
        data:
          type: object
          description: 공지사항 상세 데이터
          properties:
            id: { type: integer }
            title: { type: string }
            content: { type: string }
            author: { type: string }
            viewCount: { type: integer }
            attachments:
              type: array
              items:
                $ref: '#/components/schemas/Attachment'
            createdAt: { type: string, format: date-time }

  responses:
    BadRequestError:
      description: 잘못된 요청 데이터
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ForbiddenError:
      description: 접근 권한이 없음 (비밀번호 불일치)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFoundError:
      description: 요청한 리소스를 찾을 수 없음
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
